### ISSUE TITLE
ImportError: No module named '_file_cache'

### ISSUE THREAD

**Issue by indokely** [ChunaraLab/Fetching-Twitter-Followers#1]
Hey,

Python Version = Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
I am getting below issue. Can you please help me.

C:\Python34\devlopment\mundel\Fetching-Twitter-Followers-master>python fetch_followers.py
Traceback (most recent call last):
  File "fetch_followers.py", line 1, in <module>
    import twitter, time, json
  File "C:\Python34\devlopment\mundel\Fetching-Twitter-Followers-master\twitter__init__.py", line 31, in <module>
    from _file_cache import _FileCache
ImportError: No module named '_file_cache'

Thank you !

**Comment by anasb** [comment]
Try to `pip install python-twitter` first (or with `sudo` if you're not using a virtualenv).

**Comment by indokely** [comment]
Hey, Now i am using Python27 and getting below error

{"created_at": "Fri Apr 03 14:16:05 +0000 2015", "default_profile": true, "default_profile_image": true, "friends_count": 41, "id": 3136004156, "lang": "en", "name": "Prashansa", "profile_background_color": "C0DEED", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_tile": false, "profile_image_url": "https://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png", "profile_link_color": "0084B4", "profile_sidebar_fill_color": "DDEEF6", "profile_text_color": "333333", "protected": false, "screen_name": "prashansasims"}
Will wait 2 sec to avoid rate-limit
Fetching followers for indokely...
Will wait 1 sec to avoid rate-limit
Traceback (most recent call last):
  File "fetch_followers.py", line 35, in <module>
    friends = api.GetFollowerIDs(screen_name=name)
  File "C:\Python27\devlopment\Fetching\twitter\api.py", line 1639, in GetFollowerIDs
    next_cursor, previous_cursor, data = self.GetFollowerIDsPaged(user_id, screen_name, cursor, stringify_ids, count)
  File "C:\Python27\devlopment\Fetching\twitter\api.py", line 1581, in GetFollowerIDsPaged
    data = self._ParseAndCheckTwitter(json.content)
  File "C:\Python27\devlopment\Fetching\twitter\api.py", line 3713, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "C:\Python27\devlopment\Fetching\twitter\api.py", line 3738, in _CheckForTwitterError
    raise TwitterError(data['error'])
twitter.error.TwitterError: Not authorized.

**Comment by anasb** [comment]
This is a Twitter error (as referenced [here](https://github.com/bear/python-twitter/issues/179)), but I'm not sure what you are trying to call. Did you modify the script before running it?
Also make sure your `config` file is setup correctly.
